### ISSUE TITLE
Expand/Open User Account system

### ISSUE THREAD

**Issue by mpoegel** [mpoegel/HackRPI-Status-Board#10]
I've been considering expanding the user database system so that *everyone* would have to create an account to add a repository (as some people thought they had to do anyway). Either way, we should allow mentors to create individual accounts to greatly simplify access and control for mentors.

Pros:
* Ability for hackers to edit their repository after submitting it the first time
* Ability to collect more information about the type of project (opens the door for **LOTS** of more cool features that could be added using this data)
* Another opportunity to collect team member information
* Ability to add a repository that is not on Github
* Might be easier to integrate a team finding feature (depending on how that is done...)

Cons:
* Don't want to duplicate functionality of challenge post (or we could completely recreate all of its functionality (that we need) but I'm not sure of the residual effects of not using challenge post and also this is a huge undertaking; still possible though)
* Increases the time required to just add a repository to the database, which may discourage people from adding one in the first place, unless we made it required. For HackRPI 2014, we got 73 of 95 projects (although some may not have been Github repositories which would have prevented them from being added).

Thoughts?

**Comment by sarbos** [comment]
If this got implemented it may remove the need for challengepost as you said. I am definitely open to the idea. We should specifically bring this up at our next meeting.

**Comment by mpoegel** [comment]
Implemented hacker profiles and added framework for other profile types with #23

**Comment by mpoegel** [comment]
implemented mentor profiles with #30

**Comment by mpoegel** [comment]
Finished admin profile and other fixes with #41
