### ISSUE TITLE
Registration freezes when you select college

### ISSUE THREAD

**Issue by draab** [mpoegel/HackRPI-Status-Board#61]
When trying to register for the event, you can fill out all parts of the form except for the part that lists what college you go. At that point, it crashes as soon as you select the radio button entitled College. You cannot change any data you've previously submitted nor does it let you continue with the registration process.

For the record, I'm an RPI student so there would be no travel involved for me personally.

**Comment by mpoegel** [comment]
The list of US Colleges has been reduced from >10k to 3616. It should perform better now.
